### ISSUE TITLE
General Cleanup Suggestions

### ISSUE THREAD

**Issue by 0cjs** [wmcooper2/TotalEnglishAssistant#1]
Many of these suggestions relate to naming. If anybody else is looking at your code, or even just looking _for_ your code, poor names will mislead them and waste their time. You should always look at the names you're using for anything (variables, functions, modules, files, Git repositories, projects) and consider how they lead the readers to the right or wrong understanding.

The larger thrust is just about how well you lead people into the project. If they don't know what some part of it (or the whole thing!) is about, do they quickly find out, or are they left confused? If the latter they're going to go away rather than use your software or help you.

Specific changes:

1. This GitHub repo should be renamed to `TotalEnglishAssistant`, since [that's what you call it on PyPI](https://pypi.org/project/TotalEnglishAssistant/). So long as you don't create a new project under the old name, the old name will redirect to the new one for web and Git pull access.

2. Fix the description of this repo. 'Evolution of my coding ability after reading "Clean Code"' is way off.

3. Create a `src/` subdirectory and move all your code underneath that. This is [common practice](https://packaging.python.org/tutorials/installing-packages/#installing-from-a-local-src-tree) that will both help with the huge mess people are currently confronted with when they look at the top-level directory of the project and also make testing and packging easier and more reliable. (There are also other ways of dealing with this; you can consider changing to one of them when you know more.)

4. Start the README with a brief introduction to what this is for someone who knows nothing more than that it's a Python module. Is "Total English Assistant" a book? If so, say so and link to it. Note that this is a GUI app; I had no idea until I saw you actually run it.

5. The next section of the README should explain how to start and (briefly) use the app. It should also explain what it needs and modifies in the environment. For example, does it write out files? If so, where?

6. Add a section to the README for developers explaining how to run the tests and where things are. It doesn't have to be long (maybe even just a few sentences). The use case for this is someone discovers a bug in your code with a simple fix: how can they most quickly verify it didn't break something else? If they spent only 30 seconds coming up with the fix because they happened to see a problem while glancing at your code, they're not going to spend ten minutes figuring out how to test it. They're going to just drop the idea because it's not worth the bother.

All three README sections above should be brief and at the top of the README. If you need or want to get into deeper detail, add it in further sections below so that people coming to the project don't need to dig for the basic "What is it?", "How Do I Use It?" and "How Do I Fix It?" information.

**Comment by wmcooper2** [comment]
Thanks for the feedback. I changed the settings in my account to get the notifications. I will also make it a regular habit to check manually. I made some changes to reflect your advice. The next thing I'm having a problem with is running the "Test" script in the program's root directory. I need to read more about pytest.

**Comment by 0cjs** [comment]
For the testing stuff, have a look at [my virtualenv notes](https://github.com/0cjs/sedoc/blob/master/lang/python/runtime/virtualenv.md), particularly the [`activate`](https://raw.githubusercontent.com/0cjs/sedoc/master/lang/python/runtime/activate) script I use, and my test framework for [cpd](https://github.com/dot-home/cpd).
